name: Build MCPDisp

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          meson
          ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-jack2
        msystem: MINGW64

    - name: Build with Meson + Ninja
      shell: msys2 {0}
      run: |
        cd "${{ github.workspace }}"
        meson setup build --buildtype=release
        ninja -C build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcpdisp
        path: build/mcpdisp.exe
