name: Build MCPDisp

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-wheel
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-jack2
          mingw-w64-x86_64-fltk

    - name: Build with Meson + Ninja
      shell: msys2 {0}
      run: |
        cd "${{ github.workspace }}"
        meson setup build --buildtype=release
        ninja -C build
        
    - name: Copy runtime DLLs
      shell: msys2 {0}
      run: |
        cp /mingw64/bin/libfltk*.dll build/ || true
        cp /mingw64/bin/libjack*.dll build/ || true
        cp /mingw64/bin/libstdc++-6.dll build/
        cp /mingw64/bin/libgcc_s_seh-1.dll build/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcpdisp-win64
        path: build/